### Create a new user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email" : "gilles@bruno.com",
    "password": "mlwdkjg"
}


### Find a particular user with a given id
GET http://localhost:3000/auth/4


### Find all users with a given email
GET http://localhost:3000/auth?email=gilles@bruno.com

### Delete a user with a given id
DELETE http://localhost:3000/auth/25

### Update a user
PATCH http://localhost:3000/auth/4654
Content-Type: application/json

{
    "email" : "gilles@brunoo.com",
    "password": "new password"
}

